name: itex_pay
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.23.0
  pin_code_text_field: ^1.7.1
  flutter_multi_formatter: ^2.4.1
  flutter_easyloading: ^3.0.3
  encrypt: ^5.0.1
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
